packages: []
catalogs:
  build:
    "@ameinhardt/unocss-preset-daisy": ^1.1.8
    "@intlify/unplugin-vue-i18n": ^6.0.8
    "@unocss/eslint-config": ^66.3.2
    "@vitejs/plugin-vue": ^6.0.0
    "@vue/compiler-dom": ^3.5.17
    jsdom: ^26.1.0
    unocss: ^66.3.2
    unocss-preset-chinese: ^0.3.3
    unocss-preset-ease: ^0.0.4
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.7.0
    vite: ^7.0.0
    vite-plugin-inspect: ^11.2.0
    vite-plugin-mcp: ^0.2.2
    vite-plugin-pwa: ^1.0.0
    vite-plugin-vue-devtools: ^7.7.7
  dev:
    "@commitlint/cli": ^19.8.1
    "@commitlint/config-conventional": ^19.8.1
    "@iconify-json/mdi": ^1.2.3
    "@iconify-json/tabler": ^1.2.19
    "@kirklin/eslint-config": ^5.0.0
    "@vitest/coverage-v8": ^3.2.4
    "@vue/test-utils": ^2.4.6
    eslint: ^9.30.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-vuejs-accessibility: ^2.4.1
    husky: ^9.1.7
    lint-staged: ^16.1.2
    typescript: ^5.8.3
    vitest: ^3.2.4
    vue-tsc: ^2.2.10
  frontend:
    "@kirklin/logger": ^0.0.2
    "@kirklin/reset-css": ^0.0.6
    "@vueuse/core": ^13.4.0
    daisyui: ^5.0.43
    iso-639-1: ^3.1.5
    nprogress: ^0.2.0
    pinia: ^3.0.3
    vue: ^3.5.17
    vue-i18n: ^11.1.7
    vue-router: ^4.5.1
  types:
    "@types/node": ^24.0.6
    "@types/nprogress": ^0.2.3
