// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./../src/components/layout/Footer/index.vue')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    ITablerBrandGithub: typeof import('~icons/tabler/brand-github')['default']
    ITablerChevronDown: typeof import('~icons/tabler/chevron-down')['default']
    ITablerColorSwatch: typeof import('~icons/tabler/color-swatch')['default']
    Navbar: typeof import('./../src/components/layout/Navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeChange: typeof import('./../src/components/layout/Navbar/components/ThemeChange/index.vue')['default']
  }
}
