// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./../src/components/layout/Footer/index.vue')['default']
    Navbar: typeof import('./../src/components/layout/Navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeChange: typeof import('./../src/components/layout/Navbar/components/ThemeChange.vue')['default']
  }
}
